# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: issuer/issuer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='issuer/issuer.proto',
  package='allinbits.cosmoscash.issuer',
  syntax='proto3',
  serialized_options=_b('Z2github.com/allinbits/cosmos-cash/v3/x/issuer/types'),
  serialized_pb=_b('\n\x13issuer/issuer.proto\x12\x1b\x61llinbits.cosmoscash.issuer\"H\n\x06Issuer\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0b\n\x03\x66\x65\x65\x18\x02 \x01(\x05\x12\x12\n\nissuer_did\x18\x03 \x01(\t\x12\x0e\n\x06paused\x18\x04 \x01(\x08\x42\x34Z2github.com/allinbits/cosmos-cash/v3/x/issuer/typesb\x06proto3')
)




_ISSUER = _descriptor.Descriptor(
  name='Issuer',
  full_name='allinbits.cosmoscash.issuer.Issuer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='allinbits.cosmoscash.issuer.Issuer.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fee', full_name='allinbits.cosmoscash.issuer.Issuer.fee', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='issuer_did', full_name='allinbits.cosmoscash.issuer.Issuer.issuer_did', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='paused', full_name='allinbits.cosmoscash.issuer.Issuer.paused', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=124,
)

DESCRIPTOR.message_types_by_name['Issuer'] = _ISSUER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Issuer = _reflection.GeneratedProtocolMessageType('Issuer', (_message.Message,), dict(
  DESCRIPTOR = _ISSUER,
  __module__ = 'issuer.issuer_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.issuer.Issuer)
  ))
_sym_db.RegisterMessage(Issuer)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
