# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: issuer/query.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from cosmos.base.query.v1beta1 import pagination_pb2 as cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2
from issuer import issuer_pb2 as issuer_dot_issuer__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='issuer/query.proto',
  package='allinbits.cosmoscash.issuer',
  syntax='proto3',
  serialized_options=_b('Z2github.com/allinbits/cosmos-cash/v3/x/issuer/types'),
  serialized_pb=_b('\n\x12issuer/query.proto\x12\x1b\x61llinbits.cosmoscash.issuer\x1a\x1cgoogle/api/annotations.proto\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a\x13issuer/issuer.proto\x1a\x14gogoproto/gogo.proto\"a\n\x13QueryIssuersRequest\x12\x0e\n\x06status\x18\x01 \x01(\t\x12:\n\npagination\x18\x02 \x01(\x0b\x32&.cosmos.base.query.v1beta1.PageRequest\"\x8f\x01\n\x14QueryIssuersResponse\x12:\n\x07issuers\x18\x01 \x03(\x0b\x32#.allinbits.cosmoscash.issuer.IssuerB\x04\xc8\xde\x1f\x00\x12;\n\npagination\x18\x02 \x01(\x0b\x32\'.cosmos.base.query.v1beta1.PageResponse2\x9b\x01\n\x05Query\x12\x91\x01\n\x07Issuers\x12\x30.allinbits.cosmoscash.issuer.QueryIssuersRequest\x1a\x31.allinbits.cosmoscash.issuer.QueryIssuersResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/allinbits/issuer/issuersB4Z2github.com/allinbits/cosmos-cash/v3/x/issuer/typesb\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2.DESCRIPTOR,issuer_dot_issuer__pb2.DESCRIPTOR,gogoproto_dot_gogo__pb2.DESCRIPTOR,])




_QUERYISSUERSREQUEST = _descriptor.Descriptor(
  name='QueryIssuersRequest',
  full_name='allinbits.cosmoscash.issuer.QueryIssuersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='allinbits.cosmoscash.issuer.QueryIssuersRequest.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pagination', full_name='allinbits.cosmoscash.issuer.QueryIssuersRequest.pagination', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=265,
)


_QUERYISSUERSRESPONSE = _descriptor.Descriptor(
  name='QueryIssuersResponse',
  full_name='allinbits.cosmoscash.issuer.QueryIssuersResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='issuers', full_name='allinbits.cosmoscash.issuer.QueryIssuersResponse.issuers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pagination', full_name='allinbits.cosmoscash.issuer.QueryIssuersResponse.pagination', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=411,
)

_QUERYISSUERSREQUEST.fields_by_name['pagination'].message_type = cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2._PAGEREQUEST
_QUERYISSUERSRESPONSE.fields_by_name['issuers'].message_type = issuer_dot_issuer__pb2._ISSUER
_QUERYISSUERSRESPONSE.fields_by_name['pagination'].message_type = cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2._PAGERESPONSE
DESCRIPTOR.message_types_by_name['QueryIssuersRequest'] = _QUERYISSUERSREQUEST
DESCRIPTOR.message_types_by_name['QueryIssuersResponse'] = _QUERYISSUERSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryIssuersRequest = _reflection.GeneratedProtocolMessageType('QueryIssuersRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYISSUERSREQUEST,
  __module__ = 'issuer.query_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.issuer.QueryIssuersRequest)
  ))
_sym_db.RegisterMessage(QueryIssuersRequest)

QueryIssuersResponse = _reflection.GeneratedProtocolMessageType('QueryIssuersResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUERYISSUERSRESPONSE,
  __module__ = 'issuer.query_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.issuer.QueryIssuersResponse)
  ))
_sym_db.RegisterMessage(QueryIssuersResponse)


DESCRIPTOR._options = None
_QUERYISSUERSRESPONSE.fields_by_name['issuers']._options = None

_QUERY = _descriptor.ServiceDescriptor(
  name='Query',
  full_name='allinbits.cosmoscash.issuer.Query',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=414,
  serialized_end=569,
  methods=[
  _descriptor.MethodDescriptor(
    name='Issuers',
    full_name='allinbits.cosmoscash.issuer.Query.Issuers',
    index=0,
    containing_service=None,
    input_type=_QUERYISSUERSREQUEST,
    output_type=_QUERYISSUERSRESPONSE,
    serialized_options=_b('\202\323\344\223\002\033\022\031/allinbits/issuer/issuers'),
  ),
])
_sym_db.RegisterServiceDescriptor(_QUERY)

DESCRIPTOR.services_by_name['Query'] = _QUERY

# @@protoc_insertion_point(module_scope)
