# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: did/did.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='did/did.proto',
  package='allinbits.cosmoscash.did',
  syntax='proto3',
  serialized_options=_b('Z/github.com/allinbits/cosmos-cash/v3/x/did/types'),
  serialized_pb=_b('\n\rdid/did.proto\x12\x18\x61llinbits.cosmoscash.did\x1a\x14gogoproto/gogo.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe1\x02\n\x0b\x44idDocument\x12\'\n\x07\x63ontext\x18\x01 \x03(\tB\x16\xea\xde\x1f\x12@context,omitempty\x12\n\n\x02id\x18\x02 \x01(\t\x12\x12\n\ncontroller\x18\x03 \x03(\t\x12H\n\x12verificationMethod\x18\x04 \x03(\x0b\x32,.allinbits.cosmoscash.did.VerificationMethod\x12\x32\n\x07service\x18\x05 \x03(\x0b\x32!.allinbits.cosmoscash.did.Service\x12\x16\n\x0e\x61uthentication\x18\x06 \x03(\t\x12\x17\n\x0f\x61ssertionMethod\x18\x07 \x03(\t\x12\x14\n\x0ckeyAgreement\x18\x08 \x03(\t\x12\x1c\n\x14\x63\x61pabilityInvocation\x18\t \x03(\t\x12\x1c\n\x14\x63\x61pabilityDelegation\x18\n \x03(\t:\x08\xe8\xa0\x1f\x01\x88\xa0\x1f\x00\"\xb9\x01\n\x12VerificationMethod\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x12\n\ncontroller\x18\x03 \x01(\t\x12\x1d\n\x13\x62lockchainAccountID\x18\x04 \x01(\tH\x00\x12\x16\n\x0cpublicKeyHex\x18\x05 \x01(\tH\x00\x12\x1c\n\x12publicKeyMultibase\x18\x06 \x01(\tH\x00:\x08\xe8\xa0\x1f\x01\x88\xa0\x1f\x00\x42\x16\n\x14verificationMaterial\"F\n\x07Service\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x17\n\x0fserviceEndpoint\x18\x03 \x01(\t:\x08\xe8\xa0\x1f\x01\x88\xa0\x1f\x00\"\xa5\x01\n\x0b\x44idMetadata\x12\x11\n\tversionId\x18\x01 \x01(\t\x12\x31\n\x07\x63reated\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x04\x90\xdf\x1f\x01\x12\x31\n\x07updated\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x04\x90\xdf\x1f\x01\x12\x13\n\x0b\x64\x65\x61\x63tivated\x18\x04 \x01(\x08:\x08\xe8\xa0\x1f\x01\x88\xa0\x1f\x00\x42\x31Z/github.com/allinbits/cosmos-cash/v3/x/did/typesb\x06proto3')
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_DIDDOCUMENT = _descriptor.Descriptor(
  name='DidDocument',
  full_name='allinbits.cosmoscash.did.DidDocument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='context', full_name='allinbits.cosmoscash.did.DidDocument.context', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\352\336\037\022@context,omitempty'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='allinbits.cosmoscash.did.DidDocument.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='controller', full_name='allinbits.cosmoscash.did.DidDocument.controller', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='verificationMethod', full_name='allinbits.cosmoscash.did.DidDocument.verificationMethod', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service', full_name='allinbits.cosmoscash.did.DidDocument.service', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='authentication', full_name='allinbits.cosmoscash.did.DidDocument.authentication', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='assertionMethod', full_name='allinbits.cosmoscash.did.DidDocument.assertionMethod', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keyAgreement', full_name='allinbits.cosmoscash.did.DidDocument.keyAgreement', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='capabilityInvocation', full_name='allinbits.cosmoscash.did.DidDocument.capabilityInvocation', index=8,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='capabilityDelegation', full_name='allinbits.cosmoscash.did.DidDocument.capabilityDelegation', index=9,
      number=10, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\350\240\037\001\210\240\037\000'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=452,
)


_VERIFICATIONMETHOD = _descriptor.Descriptor(
  name='VerificationMethod',
  full_name='allinbits.cosmoscash.did.VerificationMethod',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='allinbits.cosmoscash.did.VerificationMethod.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='allinbits.cosmoscash.did.VerificationMethod.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='controller', full_name='allinbits.cosmoscash.did.VerificationMethod.controller', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blockchainAccountID', full_name='allinbits.cosmoscash.did.VerificationMethod.blockchainAccountID', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='publicKeyHex', full_name='allinbits.cosmoscash.did.VerificationMethod.publicKeyHex', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='publicKeyMultibase', full_name='allinbits.cosmoscash.did.VerificationMethod.publicKeyMultibase', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\350\240\037\001\210\240\037\000'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='verificationMaterial', full_name='allinbits.cosmoscash.did.VerificationMethod.verificationMaterial',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=455,
  serialized_end=640,
)


_SERVICE = _descriptor.Descriptor(
  name='Service',
  full_name='allinbits.cosmoscash.did.Service',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='allinbits.cosmoscash.did.Service.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='allinbits.cosmoscash.did.Service.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serviceEndpoint', full_name='allinbits.cosmoscash.did.Service.serviceEndpoint', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\350\240\037\001\210\240\037\000'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=642,
  serialized_end=712,
)


_DIDMETADATA = _descriptor.Descriptor(
  name='DidMetadata',
  full_name='allinbits.cosmoscash.did.DidMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='versionId', full_name='allinbits.cosmoscash.did.DidMetadata.versionId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created', full_name='allinbits.cosmoscash.did.DidMetadata.created', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\220\337\037\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updated', full_name='allinbits.cosmoscash.did.DidMetadata.updated', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\220\337\037\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deactivated', full_name='allinbits.cosmoscash.did.DidMetadata.deactivated', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\350\240\037\001\210\240\037\000'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=715,
  serialized_end=880,
)

_DIDDOCUMENT.fields_by_name['verificationMethod'].message_type = _VERIFICATIONMETHOD
_DIDDOCUMENT.fields_by_name['service'].message_type = _SERVICE
_VERIFICATIONMETHOD.oneofs_by_name['verificationMaterial'].fields.append(
  _VERIFICATIONMETHOD.fields_by_name['blockchainAccountID'])
_VERIFICATIONMETHOD.fields_by_name['blockchainAccountID'].containing_oneof = _VERIFICATIONMETHOD.oneofs_by_name['verificationMaterial']
_VERIFICATIONMETHOD.oneofs_by_name['verificationMaterial'].fields.append(
  _VERIFICATIONMETHOD.fields_by_name['publicKeyHex'])
_VERIFICATIONMETHOD.fields_by_name['publicKeyHex'].containing_oneof = _VERIFICATIONMETHOD.oneofs_by_name['verificationMaterial']
_VERIFICATIONMETHOD.oneofs_by_name['verificationMaterial'].fields.append(
  _VERIFICATIONMETHOD.fields_by_name['publicKeyMultibase'])
_VERIFICATIONMETHOD.fields_by_name['publicKeyMultibase'].containing_oneof = _VERIFICATIONMETHOD.oneofs_by_name['verificationMaterial']
_DIDMETADATA.fields_by_name['created'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_DIDMETADATA.fields_by_name['updated'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['DidDocument'] = _DIDDOCUMENT
DESCRIPTOR.message_types_by_name['VerificationMethod'] = _VERIFICATIONMETHOD
DESCRIPTOR.message_types_by_name['Service'] = _SERVICE
DESCRIPTOR.message_types_by_name['DidMetadata'] = _DIDMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DidDocument = _reflection.GeneratedProtocolMessageType('DidDocument', (_message.Message,), dict(
  DESCRIPTOR = _DIDDOCUMENT,
  __module__ = 'did.did_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.did.DidDocument)
  ))
_sym_db.RegisterMessage(DidDocument)

VerificationMethod = _reflection.GeneratedProtocolMessageType('VerificationMethod', (_message.Message,), dict(
  DESCRIPTOR = _VERIFICATIONMETHOD,
  __module__ = 'did.did_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.did.VerificationMethod)
  ))
_sym_db.RegisterMessage(VerificationMethod)

Service = _reflection.GeneratedProtocolMessageType('Service', (_message.Message,), dict(
  DESCRIPTOR = _SERVICE,
  __module__ = 'did.did_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.did.Service)
  ))
_sym_db.RegisterMessage(Service)

DidMetadata = _reflection.GeneratedProtocolMessageType('DidMetadata', (_message.Message,), dict(
  DESCRIPTOR = _DIDMETADATA,
  __module__ = 'did.did_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.did.DidMetadata)
  ))
_sym_db.RegisterMessage(DidMetadata)


DESCRIPTOR._options = None
_DIDDOCUMENT.fields_by_name['context']._options = None
_DIDDOCUMENT._options = None
_VERIFICATIONMETHOD._options = None
_SERVICE._options = None
_DIDMETADATA.fields_by_name['created']._options = None
_DIDMETADATA.fields_by_name['updated']._options = None
_DIDMETADATA._options = None
# @@protoc_insertion_point(module_scope)
