# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: did/event.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='did/event.proto',
  package='allinbits.cosmoscash.did',
  syntax='proto3',
  serialized_options=_b('Z/github.com/allinbits/cosmos-cash/v3/x/did/types'),
  serialized_pb=_b('\n\x0f\x64id/event.proto\x12\x18\x61llinbits.cosmoscash.did\x1a\x14gogoproto/gogo.proto\"@\n\x17\x44idDocumentCreatedEvent\x12\x0b\n\x03\x64id\x18\x01 \x01(\t\x12\x0e\n\x06signer\x18\x02 \x01(\t:\x08\xe8\xa0\x1f\x01\x88\xa0\x1f\x00\"@\n\x17\x44idDocumentUpdatedEvent\x12\x0b\n\x03\x64id\x18\x01 \x01(\t\x12\x0e\n\x06signer\x18\x02 \x01(\t:\x08\xe8\xa0\x1f\x01\x88\xa0\x1f\x00\x42\x31Z/github.com/allinbits/cosmos-cash/v3/x/did/typesb\x06proto3')
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,])




_DIDDOCUMENTCREATEDEVENT = _descriptor.Descriptor(
  name='DidDocumentCreatedEvent',
  full_name='allinbits.cosmoscash.did.DidDocumentCreatedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='did', full_name='allinbits.cosmoscash.did.DidDocumentCreatedEvent.did', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signer', full_name='allinbits.cosmoscash.did.DidDocumentCreatedEvent.signer', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\350\240\037\001\210\240\037\000'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=131,
)


_DIDDOCUMENTUPDATEDEVENT = _descriptor.Descriptor(
  name='DidDocumentUpdatedEvent',
  full_name='allinbits.cosmoscash.did.DidDocumentUpdatedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='did', full_name='allinbits.cosmoscash.did.DidDocumentUpdatedEvent.did', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signer', full_name='allinbits.cosmoscash.did.DidDocumentUpdatedEvent.signer', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\350\240\037\001\210\240\037\000'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=197,
)

DESCRIPTOR.message_types_by_name['DidDocumentCreatedEvent'] = _DIDDOCUMENTCREATEDEVENT
DESCRIPTOR.message_types_by_name['DidDocumentUpdatedEvent'] = _DIDDOCUMENTUPDATEDEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DidDocumentCreatedEvent = _reflection.GeneratedProtocolMessageType('DidDocumentCreatedEvent', (_message.Message,), dict(
  DESCRIPTOR = _DIDDOCUMENTCREATEDEVENT,
  __module__ = 'did.event_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.did.DidDocumentCreatedEvent)
  ))
_sym_db.RegisterMessage(DidDocumentCreatedEvent)

DidDocumentUpdatedEvent = _reflection.GeneratedProtocolMessageType('DidDocumentUpdatedEvent', (_message.Message,), dict(
  DESCRIPTOR = _DIDDOCUMENTUPDATEDEVENT,
  __module__ = 'did.event_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.did.DidDocumentUpdatedEvent)
  ))
_sym_db.RegisterMessage(DidDocumentUpdatedEvent)


DESCRIPTOR._options = None
_DIDDOCUMENTCREATEDEVENT._options = None
_DIDDOCUMENTUPDATEDEVENT._options = None
# @@protoc_insertion_point(module_scope)
