# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: did/query.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from cosmos.base.query.v1beta1 import pagination_pb2 as cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2
from did import did_pb2 as did_dot_did__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='did/query.proto',
  package='allinbits.cosmoscash.did',
  syntax='proto3',
  serialized_options=_b('Z/github.com/allinbits/cosmos-cash/v3/x/did/types'),
  serialized_pb=_b('\n\x0f\x64id/query.proto\x12\x18\x61llinbits.cosmoscash.did\x1a\x1cgoogle/api/annotations.proto\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a\rdid/did.proto\x1a\x14gogoproto/gogo.proto\"f\n\x18QueryDidDocumentsRequest\x12\x0e\n\x06status\x18\x01 \x01(\t\x12:\n\npagination\x18\x02 \x01(\x0b\x32&.cosmos.base.query.v1beta1.PageRequest\"\x9b\x01\n\x19QueryDidDocumentsResponse\x12\x41\n\x0c\x64idDocuments\x18\x01 \x03(\x0b\x32%.allinbits.cosmoscash.did.DidDocumentB\x04\xc8\xde\x1f\x00\x12;\n\npagination\x18\x02 \x01(\x0b\x32\'.cosmos.base.query.v1beta1.PageResponse\"%\n\x17QueryDidDocumentRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x9e\x01\n\x18QueryDidDocumentResponse\x12@\n\x0b\x64idDocument\x18\x01 \x01(\x0b\x32%.allinbits.cosmoscash.did.DidDocumentB\x04\xc8\xde\x1f\x00\x12@\n\x0b\x64idMetadata\x18\x02 \x01(\x0b\x32%.allinbits.cosmoscash.did.DidMetadataB\x04\xc8\xde\x1f\x00\"/\n\x1aQueryDidDocumentB64Request\x12\x11\n\tid_base64\x18\x01 \x01(\t\"\xa1\x01\n\x1bQueryDidDocumentB64Response\x12@\n\x0b\x64idDocument\x18\x01 \x01(\x0b\x32%.allinbits.cosmoscash.did.DidDocumentB\x04\xc8\xde\x1f\x00\x12@\n\x0b\x64idMetadata\x18\x02 \x01(\x0b\x32%.allinbits.cosmoscash.did.DidMetadataB\x04\xc8\xde\x1f\x00\x32\xe4\x03\n\x05Query\x12\x94\x01\n\x0c\x44idDocuments\x12\x32.allinbits.cosmoscash.did.QueryDidDocumentsRequest\x1a\x33.allinbits.cosmoscash.did.QueryDidDocumentsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/allinbits/did/dids\x12\x96\x01\n\x0b\x44idDocument\x12\x31.allinbits.cosmoscash.did.QueryDidDocumentRequest\x1a\x32.allinbits.cosmoscash.did.QueryDidDocumentResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/allinbits/did/dids/{id}\x12\xaa\x01\n\x0e\x44idDocumentB64\x12\x34.allinbits.cosmoscash.did.QueryDidDocumentB64Request\x1a\x35.allinbits.cosmoscash.did.QueryDidDocumentB64Response\"+\x82\xd3\xe4\x93\x02%\x12#/allinbits/did/dids/b64/{id_base64}B1Z/github.com/allinbits/cosmos-cash/v3/x/did/typesb\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2.DESCRIPTOR,did_dot_did__pb2.DESCRIPTOR,gogoproto_dot_gogo__pb2.DESCRIPTOR,])




_QUERYDIDDOCUMENTSREQUEST = _descriptor.Descriptor(
  name='QueryDidDocumentsRequest',
  full_name='allinbits.cosmoscash.did.QueryDidDocumentsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='allinbits.cosmoscash.did.QueryDidDocumentsRequest.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pagination', full_name='allinbits.cosmoscash.did.QueryDidDocumentsRequest.pagination', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=258,
)


_QUERYDIDDOCUMENTSRESPONSE = _descriptor.Descriptor(
  name='QueryDidDocumentsResponse',
  full_name='allinbits.cosmoscash.did.QueryDidDocumentsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='didDocuments', full_name='allinbits.cosmoscash.did.QueryDidDocumentsResponse.didDocuments', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pagination', full_name='allinbits.cosmoscash.did.QueryDidDocumentsResponse.pagination', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=416,
)


_QUERYDIDDOCUMENTREQUEST = _descriptor.Descriptor(
  name='QueryDidDocumentRequest',
  full_name='allinbits.cosmoscash.did.QueryDidDocumentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='allinbits.cosmoscash.did.QueryDidDocumentRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=455,
)


_QUERYDIDDOCUMENTRESPONSE = _descriptor.Descriptor(
  name='QueryDidDocumentResponse',
  full_name='allinbits.cosmoscash.did.QueryDidDocumentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='didDocument', full_name='allinbits.cosmoscash.did.QueryDidDocumentResponse.didDocument', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='didMetadata', full_name='allinbits.cosmoscash.did.QueryDidDocumentResponse.didMetadata', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=458,
  serialized_end=616,
)


_QUERYDIDDOCUMENTB64REQUEST = _descriptor.Descriptor(
  name='QueryDidDocumentB64Request',
  full_name='allinbits.cosmoscash.did.QueryDidDocumentB64Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_base64', full_name='allinbits.cosmoscash.did.QueryDidDocumentB64Request.id_base64', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=618,
  serialized_end=665,
)


_QUERYDIDDOCUMENTB64RESPONSE = _descriptor.Descriptor(
  name='QueryDidDocumentB64Response',
  full_name='allinbits.cosmoscash.did.QueryDidDocumentB64Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='didDocument', full_name='allinbits.cosmoscash.did.QueryDidDocumentB64Response.didDocument', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='didMetadata', full_name='allinbits.cosmoscash.did.QueryDidDocumentB64Response.didMetadata', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=668,
  serialized_end=829,
)

_QUERYDIDDOCUMENTSREQUEST.fields_by_name['pagination'].message_type = cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2._PAGEREQUEST
_QUERYDIDDOCUMENTSRESPONSE.fields_by_name['didDocuments'].message_type = did_dot_did__pb2._DIDDOCUMENT
_QUERYDIDDOCUMENTSRESPONSE.fields_by_name['pagination'].message_type = cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2._PAGERESPONSE
_QUERYDIDDOCUMENTRESPONSE.fields_by_name['didDocument'].message_type = did_dot_did__pb2._DIDDOCUMENT
_QUERYDIDDOCUMENTRESPONSE.fields_by_name['didMetadata'].message_type = did_dot_did__pb2._DIDMETADATA
_QUERYDIDDOCUMENTB64RESPONSE.fields_by_name['didDocument'].message_type = did_dot_did__pb2._DIDDOCUMENT
_QUERYDIDDOCUMENTB64RESPONSE.fields_by_name['didMetadata'].message_type = did_dot_did__pb2._DIDMETADATA
DESCRIPTOR.message_types_by_name['QueryDidDocumentsRequest'] = _QUERYDIDDOCUMENTSREQUEST
DESCRIPTOR.message_types_by_name['QueryDidDocumentsResponse'] = _QUERYDIDDOCUMENTSRESPONSE
DESCRIPTOR.message_types_by_name['QueryDidDocumentRequest'] = _QUERYDIDDOCUMENTREQUEST
DESCRIPTOR.message_types_by_name['QueryDidDocumentResponse'] = _QUERYDIDDOCUMENTRESPONSE
DESCRIPTOR.message_types_by_name['QueryDidDocumentB64Request'] = _QUERYDIDDOCUMENTB64REQUEST
DESCRIPTOR.message_types_by_name['QueryDidDocumentB64Response'] = _QUERYDIDDOCUMENTB64RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryDidDocumentsRequest = _reflection.GeneratedProtocolMessageType('QueryDidDocumentsRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYDIDDOCUMENTSREQUEST,
  __module__ = 'did.query_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.did.QueryDidDocumentsRequest)
  ))
_sym_db.RegisterMessage(QueryDidDocumentsRequest)

QueryDidDocumentsResponse = _reflection.GeneratedProtocolMessageType('QueryDidDocumentsResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUERYDIDDOCUMENTSRESPONSE,
  __module__ = 'did.query_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.did.QueryDidDocumentsResponse)
  ))
_sym_db.RegisterMessage(QueryDidDocumentsResponse)

QueryDidDocumentRequest = _reflection.GeneratedProtocolMessageType('QueryDidDocumentRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYDIDDOCUMENTREQUEST,
  __module__ = 'did.query_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.did.QueryDidDocumentRequest)
  ))
_sym_db.RegisterMessage(QueryDidDocumentRequest)

QueryDidDocumentResponse = _reflection.GeneratedProtocolMessageType('QueryDidDocumentResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUERYDIDDOCUMENTRESPONSE,
  __module__ = 'did.query_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.did.QueryDidDocumentResponse)
  ))
_sym_db.RegisterMessage(QueryDidDocumentResponse)

QueryDidDocumentB64Request = _reflection.GeneratedProtocolMessageType('QueryDidDocumentB64Request', (_message.Message,), dict(
  DESCRIPTOR = _QUERYDIDDOCUMENTB64REQUEST,
  __module__ = 'did.query_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.did.QueryDidDocumentB64Request)
  ))
_sym_db.RegisterMessage(QueryDidDocumentB64Request)

QueryDidDocumentB64Response = _reflection.GeneratedProtocolMessageType('QueryDidDocumentB64Response', (_message.Message,), dict(
  DESCRIPTOR = _QUERYDIDDOCUMENTB64RESPONSE,
  __module__ = 'did.query_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.did.QueryDidDocumentB64Response)
  ))
_sym_db.RegisterMessage(QueryDidDocumentB64Response)


DESCRIPTOR._options = None
_QUERYDIDDOCUMENTSRESPONSE.fields_by_name['didDocuments']._options = None
_QUERYDIDDOCUMENTRESPONSE.fields_by_name['didDocument']._options = None
_QUERYDIDDOCUMENTRESPONSE.fields_by_name['didMetadata']._options = None
_QUERYDIDDOCUMENTB64RESPONSE.fields_by_name['didDocument']._options = None
_QUERYDIDDOCUMENTB64RESPONSE.fields_by_name['didMetadata']._options = None

_QUERY = _descriptor.ServiceDescriptor(
  name='Query',
  full_name='allinbits.cosmoscash.did.Query',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=832,
  serialized_end=1316,
  methods=[
  _descriptor.MethodDescriptor(
    name='DidDocuments',
    full_name='allinbits.cosmoscash.did.Query.DidDocuments',
    index=0,
    containing_service=None,
    input_type=_QUERYDIDDOCUMENTSREQUEST,
    output_type=_QUERYDIDDOCUMENTSRESPONSE,
    serialized_options=_b('\202\323\344\223\002\025\022\023/allinbits/did/dids'),
  ),
  _descriptor.MethodDescriptor(
    name='DidDocument',
    full_name='allinbits.cosmoscash.did.Query.DidDocument',
    index=1,
    containing_service=None,
    input_type=_QUERYDIDDOCUMENTREQUEST,
    output_type=_QUERYDIDDOCUMENTRESPONSE,
    serialized_options=_b('\202\323\344\223\002\032\022\030/allinbits/did/dids/{id}'),
  ),
  _descriptor.MethodDescriptor(
    name='DidDocumentB64',
    full_name='allinbits.cosmoscash.did.Query.DidDocumentB64',
    index=2,
    containing_service=None,
    input_type=_QUERYDIDDOCUMENTB64REQUEST,
    output_type=_QUERYDIDDOCUMENTB64RESPONSE,
    serialized_options=_b('\202\323\344\223\002%\022#/allinbits/did/dids/b64/{id_base64}'),
  ),
])
_sym_db.RegisterServiceDescriptor(_QUERY)

DESCRIPTOR.services_by_name['Query'] = _QUERY

# @@protoc_insertion_point(module_scope)
