# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: verifiable-credential/query.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from cosmos.base.query.v1beta1 import pagination_pb2 as cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2
from verifiable_credential import verifiable_credential_pb2 as verifiable__credential_dot_verifiable__credential__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='verifiable-credential/query.proto',
  package='allinbits.cosmoscash.verifiablecredential',
  syntax='proto3',
  serialized_options=_b('ZAgithub.com/allinbits/cosmos-cash/v3/x/verifiable-credential/types'),
  serialized_pb=_b('\n!verifiable-credential/query.proto\x12)allinbits.cosmoscash.verifiablecredential\x1a\x1cgoogle/api/annotations.proto\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a\x31verifiable-credential/verifiable-credential.proto\x1a\x14gogoproto/gogo.proto\"o\n!QueryVerifiableCredentialsRequest\x12\x0e\n\x06status\x18\x01 \x01(\t\x12:\n\npagination\x18\x02 \x01(\x0b\x32&.cosmos.base.query.v1beta1.PageRequest\"\xb5\x01\n\"QueryVerifiableCredentialsResponse\x12R\n\x03vcs\x18\x01 \x03(\x0b\x32?.allinbits.cosmoscash.verifiablecredential.VerifiableCredentialB\x04\xc8\xde\x1f\x00\x12;\n\npagination\x18\x02 \x01(\x0b\x32\'.cosmos.base.query.v1beta1.PageResponse\"D\n QueryVerifiableCredentialRequest\x12 \n\x18verifiable_credential_id\x18\x01 \x01(\t\"\x89\x01\n!QueryVerifiableCredentialResponse\x12\x64\n\x15verifiable_credential\x18\x01 \x01(\x0b\x32?.allinbits.cosmoscash.verifiablecredential.VerifiableCredentialB\x04\xc8\xde\x1f\x00\"=\n)QueryValidateVerifiableCredentialResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x32\x8d\x04\n\x05Query\x12\xf4\x01\n\x15VerifiableCredentials\x12L.allinbits.cosmoscash.verifiablecredential.QueryVerifiableCredentialsRequest\x1aM.allinbits.cosmoscash.verifiablecredential.QueryVerifiableCredentialsResponse\">\x82\xd3\xe4\x93\x02\x38\x12\x36/allinbits/verifiablecredentials/verifiablecredentials\x12\x8c\x02\n\x14VerifiableCredential\x12K.allinbits.cosmoscash.verifiablecredential.QueryVerifiableCredentialRequest\x1aL.allinbits.cosmoscash.verifiablecredential.QueryVerifiableCredentialResponse\"Y\x82\xd3\xe4\x93\x02S\x12Q/allinbits/verifiablecredentials/verifiablecredentials/{verifiable_credential_id}BCZAgithub.com/allinbits/cosmos-cash/v3/x/verifiable-credential/typesb\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2.DESCRIPTOR,verifiable__credential_dot_verifiable__credential__pb2.DESCRIPTOR,gogoproto_dot_gogo__pb2.DESCRIPTOR,])




_QUERYVERIFIABLECREDENTIALSREQUEST = _descriptor.Descriptor(
  name='QueryVerifiableCredentialsRequest',
  full_name='allinbits.cosmoscash.verifiablecredential.QueryVerifiableCredentialsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='allinbits.cosmoscash.verifiablecredential.QueryVerifiableCredentialsRequest.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pagination', full_name='allinbits.cosmoscash.verifiablecredential.QueryVerifiableCredentialsRequest.pagination', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=338,
)


_QUERYVERIFIABLECREDENTIALSRESPONSE = _descriptor.Descriptor(
  name='QueryVerifiableCredentialsResponse',
  full_name='allinbits.cosmoscash.verifiablecredential.QueryVerifiableCredentialsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vcs', full_name='allinbits.cosmoscash.verifiablecredential.QueryVerifiableCredentialsResponse.vcs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pagination', full_name='allinbits.cosmoscash.verifiablecredential.QueryVerifiableCredentialsResponse.pagination', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=522,
)


_QUERYVERIFIABLECREDENTIALREQUEST = _descriptor.Descriptor(
  name='QueryVerifiableCredentialRequest',
  full_name='allinbits.cosmoscash.verifiablecredential.QueryVerifiableCredentialRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='verifiable_credential_id', full_name='allinbits.cosmoscash.verifiablecredential.QueryVerifiableCredentialRequest.verifiable_credential_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=524,
  serialized_end=592,
)


_QUERYVERIFIABLECREDENTIALRESPONSE = _descriptor.Descriptor(
  name='QueryVerifiableCredentialResponse',
  full_name='allinbits.cosmoscash.verifiablecredential.QueryVerifiableCredentialResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='verifiable_credential', full_name='allinbits.cosmoscash.verifiablecredential.QueryVerifiableCredentialResponse.verifiable_credential', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=595,
  serialized_end=732,
)


_QUERYVALIDATEVERIFIABLECREDENTIALRESPONSE = _descriptor.Descriptor(
  name='QueryValidateVerifiableCredentialResponse',
  full_name='allinbits.cosmoscash.verifiablecredential.QueryValidateVerifiableCredentialResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_valid', full_name='allinbits.cosmoscash.verifiablecredential.QueryValidateVerifiableCredentialResponse.is_valid', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=734,
  serialized_end=795,
)

_QUERYVERIFIABLECREDENTIALSREQUEST.fields_by_name['pagination'].message_type = cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2._PAGEREQUEST
_QUERYVERIFIABLECREDENTIALSRESPONSE.fields_by_name['vcs'].message_type = verifiable__credential_dot_verifiable__credential__pb2._VERIFIABLECREDENTIAL
_QUERYVERIFIABLECREDENTIALSRESPONSE.fields_by_name['pagination'].message_type = cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2._PAGERESPONSE
_QUERYVERIFIABLECREDENTIALRESPONSE.fields_by_name['verifiable_credential'].message_type = verifiable__credential_dot_verifiable__credential__pb2._VERIFIABLECREDENTIAL
DESCRIPTOR.message_types_by_name['QueryVerifiableCredentialsRequest'] = _QUERYVERIFIABLECREDENTIALSREQUEST
DESCRIPTOR.message_types_by_name['QueryVerifiableCredentialsResponse'] = _QUERYVERIFIABLECREDENTIALSRESPONSE
DESCRIPTOR.message_types_by_name['QueryVerifiableCredentialRequest'] = _QUERYVERIFIABLECREDENTIALREQUEST
DESCRIPTOR.message_types_by_name['QueryVerifiableCredentialResponse'] = _QUERYVERIFIABLECREDENTIALRESPONSE
DESCRIPTOR.message_types_by_name['QueryValidateVerifiableCredentialResponse'] = _QUERYVALIDATEVERIFIABLECREDENTIALRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryVerifiableCredentialsRequest = _reflection.GeneratedProtocolMessageType('QueryVerifiableCredentialsRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYVERIFIABLECREDENTIALSREQUEST,
  __module__ = 'verifiable_credential.query_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.verifiablecredential.QueryVerifiableCredentialsRequest)
  ))
_sym_db.RegisterMessage(QueryVerifiableCredentialsRequest)

QueryVerifiableCredentialsResponse = _reflection.GeneratedProtocolMessageType('QueryVerifiableCredentialsResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUERYVERIFIABLECREDENTIALSRESPONSE,
  __module__ = 'verifiable_credential.query_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.verifiablecredential.QueryVerifiableCredentialsResponse)
  ))
_sym_db.RegisterMessage(QueryVerifiableCredentialsResponse)

QueryVerifiableCredentialRequest = _reflection.GeneratedProtocolMessageType('QueryVerifiableCredentialRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYVERIFIABLECREDENTIALREQUEST,
  __module__ = 'verifiable_credential.query_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.verifiablecredential.QueryVerifiableCredentialRequest)
  ))
_sym_db.RegisterMessage(QueryVerifiableCredentialRequest)

QueryVerifiableCredentialResponse = _reflection.GeneratedProtocolMessageType('QueryVerifiableCredentialResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUERYVERIFIABLECREDENTIALRESPONSE,
  __module__ = 'verifiable_credential.query_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.verifiablecredential.QueryVerifiableCredentialResponse)
  ))
_sym_db.RegisterMessage(QueryVerifiableCredentialResponse)

QueryValidateVerifiableCredentialResponse = _reflection.GeneratedProtocolMessageType('QueryValidateVerifiableCredentialResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUERYVALIDATEVERIFIABLECREDENTIALRESPONSE,
  __module__ = 'verifiable_credential.query_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.verifiablecredential.QueryValidateVerifiableCredentialResponse)
  ))
_sym_db.RegisterMessage(QueryValidateVerifiableCredentialResponse)


DESCRIPTOR._options = None
_QUERYVERIFIABLECREDENTIALSRESPONSE.fields_by_name['vcs']._options = None
_QUERYVERIFIABLECREDENTIALRESPONSE.fields_by_name['verifiable_credential']._options = None

_QUERY = _descriptor.ServiceDescriptor(
  name='Query',
  full_name='allinbits.cosmoscash.verifiablecredential.Query',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=798,
  serialized_end=1323,
  methods=[
  _descriptor.MethodDescriptor(
    name='VerifiableCredentials',
    full_name='allinbits.cosmoscash.verifiablecredential.Query.VerifiableCredentials',
    index=0,
    containing_service=None,
    input_type=_QUERYVERIFIABLECREDENTIALSREQUEST,
    output_type=_QUERYVERIFIABLECREDENTIALSRESPONSE,
    serialized_options=_b('\202\323\344\223\0028\0226/allinbits/verifiablecredentials/verifiablecredentials'),
  ),
  _descriptor.MethodDescriptor(
    name='VerifiableCredential',
    full_name='allinbits.cosmoscash.verifiablecredential.Query.VerifiableCredential',
    index=1,
    containing_service=None,
    input_type=_QUERYVERIFIABLECREDENTIALREQUEST,
    output_type=_QUERYVERIFIABLECREDENTIALRESPONSE,
    serialized_options=_b('\202\323\344\223\002S\022Q/allinbits/verifiablecredentials/verifiablecredentials/{verifiable_credential_id}'),
  ),
])
_sym_db.RegisterServiceDescriptor(_QUERY)

DESCRIPTOR.services_by_name['Query'] = _QUERY

# @@protoc_insertion_point(module_scope)
