# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: verifiable-credential/tx.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from verifiable_credential import verifiable_credential_pb2 as verifiable__credential_dot_verifiable__credential__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='verifiable-credential/tx.proto',
  package='allinbits.cosmoscash.verifiablecredential',
  syntax='proto3',
  serialized_options=_b('ZAgithub.com/allinbits/cosmos-cash/v3/x/verifiable-credential/types'),
  serialized_pb=_b('\n\x1everifiable-credential/tx.proto\x12)allinbits.cosmoscash.verifiablecredential\x1a\x14gogoproto/gogo.proto\x1a\x31verifiable-credential/verifiable-credential.proto\"E\n\x13MsgRevokeCredential\x12\x15\n\rcredential_id\x18\x01 \x01(\t\x12\r\n\x05owner\x18\x02 \x01(\t:\x08\xe8\xa0\x1f\x00\x88\xa0\x1f\x00\"\x1d\n\x1bMsgRevokeCredentialResponse\"\x82\x01\n\x12MsgIssueCredential\x12S\n\ncredential\x18\x01 \x01(\x0b\x32?.allinbits.cosmoscash.verifiablecredential.VerifiableCredential\x12\r\n\x05owner\x18\x02 \x01(\t:\x08\xe8\xa0\x1f\x00\x88\xa0\x1f\x00\"\x1c\n\x1aMsgIssueCredentialResponse2\xbc\x02\n\x03Msg\x12\x9a\x01\n\x10RevokeCredential\x12>.allinbits.cosmoscash.verifiablecredential.MsgRevokeCredential\x1a\x46.allinbits.cosmoscash.verifiablecredential.MsgRevokeCredentialResponse\x12\x97\x01\n\x0fIssueCredential\x12=.allinbits.cosmoscash.verifiablecredential.MsgIssueCredential\x1a\x45.allinbits.cosmoscash.verifiablecredential.MsgIssueCredentialResponseBCZAgithub.com/allinbits/cosmos-cash/v3/x/verifiable-credential/typesb\x06proto3')
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,verifiable__credential_dot_verifiable__credential__pb2.DESCRIPTOR,])




_MSGREVOKECREDENTIAL = _descriptor.Descriptor(
  name='MsgRevokeCredential',
  full_name='allinbits.cosmoscash.verifiablecredential.MsgRevokeCredential',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='credential_id', full_name='allinbits.cosmoscash.verifiablecredential.MsgRevokeCredential.credential_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='owner', full_name='allinbits.cosmoscash.verifiablecredential.MsgRevokeCredential.owner', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\350\240\037\000\210\240\037\000'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=219,
)


_MSGREVOKECREDENTIALRESPONSE = _descriptor.Descriptor(
  name='MsgRevokeCredentialResponse',
  full_name='allinbits.cosmoscash.verifiablecredential.MsgRevokeCredentialResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=250,
)


_MSGISSUECREDENTIAL = _descriptor.Descriptor(
  name='MsgIssueCredential',
  full_name='allinbits.cosmoscash.verifiablecredential.MsgIssueCredential',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='credential', full_name='allinbits.cosmoscash.verifiablecredential.MsgIssueCredential.credential', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='owner', full_name='allinbits.cosmoscash.verifiablecredential.MsgIssueCredential.owner', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\350\240\037\000\210\240\037\000'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=383,
)


_MSGISSUECREDENTIALRESPONSE = _descriptor.Descriptor(
  name='MsgIssueCredentialResponse',
  full_name='allinbits.cosmoscash.verifiablecredential.MsgIssueCredentialResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=413,
)

_MSGISSUECREDENTIAL.fields_by_name['credential'].message_type = verifiable__credential_dot_verifiable__credential__pb2._VERIFIABLECREDENTIAL
DESCRIPTOR.message_types_by_name['MsgRevokeCredential'] = _MSGREVOKECREDENTIAL
DESCRIPTOR.message_types_by_name['MsgRevokeCredentialResponse'] = _MSGREVOKECREDENTIALRESPONSE
DESCRIPTOR.message_types_by_name['MsgIssueCredential'] = _MSGISSUECREDENTIAL
DESCRIPTOR.message_types_by_name['MsgIssueCredentialResponse'] = _MSGISSUECREDENTIALRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgRevokeCredential = _reflection.GeneratedProtocolMessageType('MsgRevokeCredential', (_message.Message,), dict(
  DESCRIPTOR = _MSGREVOKECREDENTIAL,
  __module__ = 'verifiable_credential.tx_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.verifiablecredential.MsgRevokeCredential)
  ))
_sym_db.RegisterMessage(MsgRevokeCredential)

MsgRevokeCredentialResponse = _reflection.GeneratedProtocolMessageType('MsgRevokeCredentialResponse', (_message.Message,), dict(
  DESCRIPTOR = _MSGREVOKECREDENTIALRESPONSE,
  __module__ = 'verifiable_credential.tx_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.verifiablecredential.MsgRevokeCredentialResponse)
  ))
_sym_db.RegisterMessage(MsgRevokeCredentialResponse)

MsgIssueCredential = _reflection.GeneratedProtocolMessageType('MsgIssueCredential', (_message.Message,), dict(
  DESCRIPTOR = _MSGISSUECREDENTIAL,
  __module__ = 'verifiable_credential.tx_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.verifiablecredential.MsgIssueCredential)
  ))
_sym_db.RegisterMessage(MsgIssueCredential)

MsgIssueCredentialResponse = _reflection.GeneratedProtocolMessageType('MsgIssueCredentialResponse', (_message.Message,), dict(
  DESCRIPTOR = _MSGISSUECREDENTIALRESPONSE,
  __module__ = 'verifiable_credential.tx_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.verifiablecredential.MsgIssueCredentialResponse)
  ))
_sym_db.RegisterMessage(MsgIssueCredentialResponse)


DESCRIPTOR._options = None
_MSGREVOKECREDENTIAL._options = None
_MSGISSUECREDENTIAL._options = None

_MSG = _descriptor.ServiceDescriptor(
  name='Msg',
  full_name='allinbits.cosmoscash.verifiablecredential.Msg',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=416,
  serialized_end=732,
  methods=[
  _descriptor.MethodDescriptor(
    name='RevokeCredential',
    full_name='allinbits.cosmoscash.verifiablecredential.Msg.RevokeCredential',
    index=0,
    containing_service=None,
    input_type=_MSGREVOKECREDENTIAL,
    output_type=_MSGREVOKECREDENTIALRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='IssueCredential',
    full_name='allinbits.cosmoscash.verifiablecredential.Msg.IssueCredential',
    index=1,
    containing_service=None,
    input_type=_MSGISSUECREDENTIAL,
    output_type=_MSGISSUECREDENTIALRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MSG)

DESCRIPTOR.services_by_name['Msg'] = _MSG

# @@protoc_insertion_point(module_scope)
