# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: regulator/genesis.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='regulator/genesis.proto',
  package='allinbits.cosmoscash.regulator',
  syntax='proto3',
  serialized_options=_b('Z5github.com/allinbits/cosmos-cash/v3/x/regulator/types'),
  serialized_pb=_b('\n\x17regulator/genesis.proto\x12\x1e\x61llinbits.cosmoscash.regulator\x1a\x14gogoproto/gogo.proto\"N\n\x0cGenesisState\x12>\n\nregulators\x18\x01 \x01(\x0b\x32*.allinbits.cosmoscash.regulator.Regulators\"\xbd\x01\n\nRegulators\x12>\n\taddresses\x18\x01 \x03(\tB+\xea\xde\x1f\x13\x61\x64\x64resses,omitempty\xf2\xde\x1f\x10yaml:\"addresses\"\x12\x42\n\x04\x64ids\x18\x02 \x03(\x0b\x32\x34.allinbits.cosmoscash.regulator.Regulators.DidsEntry\x1a+\n\tDidsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x37Z5github.com/allinbits/cosmos-cash/v3/x/regulator/typesb\x06proto3')
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,])




_GENESISSTATE = _descriptor.Descriptor(
  name='GenesisState',
  full_name='allinbits.cosmoscash.regulator.GenesisState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='regulators', full_name='allinbits.cosmoscash.regulator.GenesisState.regulators', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=159,
)


_REGULATORS_DIDSENTRY = _descriptor.Descriptor(
  name='DidsEntry',
  full_name='allinbits.cosmoscash.regulator.Regulators.DidsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='allinbits.cosmoscash.regulator.Regulators.DidsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='allinbits.cosmoscash.regulator.Regulators.DidsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=351,
)

_REGULATORS = _descriptor.Descriptor(
  name='Regulators',
  full_name='allinbits.cosmoscash.regulator.Regulators',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='addresses', full_name='allinbits.cosmoscash.regulator.Regulators.addresses', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\352\336\037\023addresses,omitempty\362\336\037\020yaml:\"addresses\"'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dids', full_name='allinbits.cosmoscash.regulator.Regulators.dids', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_REGULATORS_DIDSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=351,
)

_GENESISSTATE.fields_by_name['regulators'].message_type = _REGULATORS
_REGULATORS_DIDSENTRY.containing_type = _REGULATORS
_REGULATORS.fields_by_name['dids'].message_type = _REGULATORS_DIDSENTRY
DESCRIPTOR.message_types_by_name['GenesisState'] = _GENESISSTATE
DESCRIPTOR.message_types_by_name['Regulators'] = _REGULATORS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenesisState = _reflection.GeneratedProtocolMessageType('GenesisState', (_message.Message,), dict(
  DESCRIPTOR = _GENESISSTATE,
  __module__ = 'regulator.genesis_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.regulator.GenesisState)
  ))
_sym_db.RegisterMessage(GenesisState)

Regulators = _reflection.GeneratedProtocolMessageType('Regulators', (_message.Message,), dict(

  DidsEntry = _reflection.GeneratedProtocolMessageType('DidsEntry', (_message.Message,), dict(
    DESCRIPTOR = _REGULATORS_DIDSENTRY,
    __module__ = 'regulator.genesis_pb2'
    # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.regulator.Regulators.DidsEntry)
    ))
  ,
  DESCRIPTOR = _REGULATORS,
  __module__ = 'regulator.genesis_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.regulator.Regulators)
  ))
_sym_db.RegisterMessage(Regulators)
_sym_db.RegisterMessage(Regulators.DidsEntry)


DESCRIPTOR._options = None
_REGULATORS_DIDSENTRY._options = None
_REGULATORS.fields_by_name['addresses']._options = None
# @@protoc_insertion_point(module_scope)
