# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: regulator/tx.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from verifiable_credential import verifiable_credential_pb2 as verifiable__credential_dot_verifiable__credential__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='regulator/tx.proto',
  package='allinbits.cosmoscash.regulator',
  syntax='proto3',
  serialized_options=_b('Z5github.com/allinbits/cosmos-cash/v3/x/regulator/types'),
  serialized_pb=_b('\n\x12regulator/tx.proto\x12\x1e\x61llinbits.cosmoscash.regulator\x1a\x14gogoproto/gogo.proto\x1a\x31verifiable-credential/verifiable-credential.proto\"\x8b\x01\n\x1bMsgIssueRegulatorCredential\x12S\n\ncredential\x18\x01 \x01(\x0b\x32?.allinbits.cosmoscash.verifiablecredential.VerifiableCredential\x12\r\n\x05owner\x18\x02 \x01(\t:\x08\xe8\xa0\x1f\x00\x88\xa0\x1f\x00\"%\n#MsgIssueRegulatorCredentialResponse\"\x8e\x01\n\x1eMsgIssueRegistrationCredential\x12S\n\ncredential\x18\x01 \x01(\x0b\x32?.allinbits.cosmoscash.verifiablecredential.VerifiableCredential\x12\r\n\x05owner\x18\x02 \x01(\t:\x08\xe8\xa0\x1f\x00\x88\xa0\x1f\x00\"(\n&MsgIssueRegistrationCredentialResponse\"\x89\x01\n\x19MsgIssueLicenseCredential\x12S\n\ncredential\x18\x01 \x01(\x0b\x32?.allinbits.cosmoscash.verifiablecredential.VerifiableCredential\x12\r\n\x05owner\x18\x02 \x01(\t:\x08\xe8\xa0\x1f\x00\x88\xa0\x1f\x00\"#\n!MsgIssueLicenseCredentialResponse2\xe5\x03\n\x03Msg\x12\x9c\x01\n\x18IssueRegulatorCredential\x12;.allinbits.cosmoscash.regulator.MsgIssueRegulatorCredential\x1a\x43.allinbits.cosmoscash.regulator.MsgIssueRegulatorCredentialResponse\x12\xa5\x01\n\x1bIssueRegistrationCredential\x12>.allinbits.cosmoscash.regulator.MsgIssueRegistrationCredential\x1a\x46.allinbits.cosmoscash.regulator.MsgIssueRegistrationCredentialResponse\x12\x96\x01\n\x16IssueLicenseCredential\x12\x39.allinbits.cosmoscash.regulator.MsgIssueLicenseCredential\x1a\x41.allinbits.cosmoscash.regulator.MsgIssueLicenseCredentialResponseB7Z5github.com/allinbits/cosmos-cash/v3/x/regulator/typesb\x06proto3')
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,verifiable__credential_dot_verifiable__credential__pb2.DESCRIPTOR,])




_MSGISSUEREGULATORCREDENTIAL = _descriptor.Descriptor(
  name='MsgIssueRegulatorCredential',
  full_name='allinbits.cosmoscash.regulator.MsgIssueRegulatorCredential',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='credential', full_name='allinbits.cosmoscash.regulator.MsgIssueRegulatorCredential.credential', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='owner', full_name='allinbits.cosmoscash.regulator.MsgIssueRegulatorCredential.owner', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\350\240\037\000\210\240\037\000'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=267,
)


_MSGISSUEREGULATORCREDENTIALRESPONSE = _descriptor.Descriptor(
  name='MsgIssueRegulatorCredentialResponse',
  full_name='allinbits.cosmoscash.regulator.MsgIssueRegulatorCredentialResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=306,
)


_MSGISSUEREGISTRATIONCREDENTIAL = _descriptor.Descriptor(
  name='MsgIssueRegistrationCredential',
  full_name='allinbits.cosmoscash.regulator.MsgIssueRegistrationCredential',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='credential', full_name='allinbits.cosmoscash.regulator.MsgIssueRegistrationCredential.credential', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='owner', full_name='allinbits.cosmoscash.regulator.MsgIssueRegistrationCredential.owner', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\350\240\037\000\210\240\037\000'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=451,
)


_MSGISSUEREGISTRATIONCREDENTIALRESPONSE = _descriptor.Descriptor(
  name='MsgIssueRegistrationCredentialResponse',
  full_name='allinbits.cosmoscash.regulator.MsgIssueRegistrationCredentialResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=453,
  serialized_end=493,
)


_MSGISSUELICENSECREDENTIAL = _descriptor.Descriptor(
  name='MsgIssueLicenseCredential',
  full_name='allinbits.cosmoscash.regulator.MsgIssueLicenseCredential',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='credential', full_name='allinbits.cosmoscash.regulator.MsgIssueLicenseCredential.credential', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='owner', full_name='allinbits.cosmoscash.regulator.MsgIssueLicenseCredential.owner', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\350\240\037\000\210\240\037\000'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=496,
  serialized_end=633,
)


_MSGISSUELICENSECREDENTIALRESPONSE = _descriptor.Descriptor(
  name='MsgIssueLicenseCredentialResponse',
  full_name='allinbits.cosmoscash.regulator.MsgIssueLicenseCredentialResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=635,
  serialized_end=670,
)

_MSGISSUEREGULATORCREDENTIAL.fields_by_name['credential'].message_type = verifiable__credential_dot_verifiable__credential__pb2._VERIFIABLECREDENTIAL
_MSGISSUEREGISTRATIONCREDENTIAL.fields_by_name['credential'].message_type = verifiable__credential_dot_verifiable__credential__pb2._VERIFIABLECREDENTIAL
_MSGISSUELICENSECREDENTIAL.fields_by_name['credential'].message_type = verifiable__credential_dot_verifiable__credential__pb2._VERIFIABLECREDENTIAL
DESCRIPTOR.message_types_by_name['MsgIssueRegulatorCredential'] = _MSGISSUEREGULATORCREDENTIAL
DESCRIPTOR.message_types_by_name['MsgIssueRegulatorCredentialResponse'] = _MSGISSUEREGULATORCREDENTIALRESPONSE
DESCRIPTOR.message_types_by_name['MsgIssueRegistrationCredential'] = _MSGISSUEREGISTRATIONCREDENTIAL
DESCRIPTOR.message_types_by_name['MsgIssueRegistrationCredentialResponse'] = _MSGISSUEREGISTRATIONCREDENTIALRESPONSE
DESCRIPTOR.message_types_by_name['MsgIssueLicenseCredential'] = _MSGISSUELICENSECREDENTIAL
DESCRIPTOR.message_types_by_name['MsgIssueLicenseCredentialResponse'] = _MSGISSUELICENSECREDENTIALRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgIssueRegulatorCredential = _reflection.GeneratedProtocolMessageType('MsgIssueRegulatorCredential', (_message.Message,), dict(
  DESCRIPTOR = _MSGISSUEREGULATORCREDENTIAL,
  __module__ = 'regulator.tx_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.regulator.MsgIssueRegulatorCredential)
  ))
_sym_db.RegisterMessage(MsgIssueRegulatorCredential)

MsgIssueRegulatorCredentialResponse = _reflection.GeneratedProtocolMessageType('MsgIssueRegulatorCredentialResponse', (_message.Message,), dict(
  DESCRIPTOR = _MSGISSUEREGULATORCREDENTIALRESPONSE,
  __module__ = 'regulator.tx_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.regulator.MsgIssueRegulatorCredentialResponse)
  ))
_sym_db.RegisterMessage(MsgIssueRegulatorCredentialResponse)

MsgIssueRegistrationCredential = _reflection.GeneratedProtocolMessageType('MsgIssueRegistrationCredential', (_message.Message,), dict(
  DESCRIPTOR = _MSGISSUEREGISTRATIONCREDENTIAL,
  __module__ = 'regulator.tx_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.regulator.MsgIssueRegistrationCredential)
  ))
_sym_db.RegisterMessage(MsgIssueRegistrationCredential)

MsgIssueRegistrationCredentialResponse = _reflection.GeneratedProtocolMessageType('MsgIssueRegistrationCredentialResponse', (_message.Message,), dict(
  DESCRIPTOR = _MSGISSUEREGISTRATIONCREDENTIALRESPONSE,
  __module__ = 'regulator.tx_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.regulator.MsgIssueRegistrationCredentialResponse)
  ))
_sym_db.RegisterMessage(MsgIssueRegistrationCredentialResponse)

MsgIssueLicenseCredential = _reflection.GeneratedProtocolMessageType('MsgIssueLicenseCredential', (_message.Message,), dict(
  DESCRIPTOR = _MSGISSUELICENSECREDENTIAL,
  __module__ = 'regulator.tx_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.regulator.MsgIssueLicenseCredential)
  ))
_sym_db.RegisterMessage(MsgIssueLicenseCredential)

MsgIssueLicenseCredentialResponse = _reflection.GeneratedProtocolMessageType('MsgIssueLicenseCredentialResponse', (_message.Message,), dict(
  DESCRIPTOR = _MSGISSUELICENSECREDENTIALRESPONSE,
  __module__ = 'regulator.tx_pb2'
  # @@protoc_insertion_point(class_scope:allinbits.cosmoscash.regulator.MsgIssueLicenseCredentialResponse)
  ))
_sym_db.RegisterMessage(MsgIssueLicenseCredentialResponse)


DESCRIPTOR._options = None
_MSGISSUEREGULATORCREDENTIAL._options = None
_MSGISSUEREGISTRATIONCREDENTIAL._options = None
_MSGISSUELICENSECREDENTIAL._options = None

_MSG = _descriptor.ServiceDescriptor(
  name='Msg',
  full_name='allinbits.cosmoscash.regulator.Msg',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=673,
  serialized_end=1158,
  methods=[
  _descriptor.MethodDescriptor(
    name='IssueRegulatorCredential',
    full_name='allinbits.cosmoscash.regulator.Msg.IssueRegulatorCredential',
    index=0,
    containing_service=None,
    input_type=_MSGISSUEREGULATORCREDENTIAL,
    output_type=_MSGISSUEREGULATORCREDENTIALRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='IssueRegistrationCredential',
    full_name='allinbits.cosmoscash.regulator.Msg.IssueRegistrationCredential',
    index=1,
    containing_service=None,
    input_type=_MSGISSUEREGISTRATIONCREDENTIAL,
    output_type=_MSGISSUEREGISTRATIONCREDENTIALRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='IssueLicenseCredential',
    full_name='allinbits.cosmoscash.regulator.Msg.IssueLicenseCredential',
    index=2,
    containing_service=None,
    input_type=_MSGISSUELICENSECREDENTIAL,
    output_type=_MSGISSUELICENSECREDENTIALRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MSG)

DESCRIPTOR.services_by_name['Msg'] = _MSG

# @@protoc_insertion_point(module_scope)
